# roles/bind/tasks/main.yml
---

- name: Check whether `bind_zone_master_server_ip` was set
  assert:
    that: bind_zone_master_server_ip is defined

- name: Install BIND
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: "{{ bind_packages }}"
  tags: bind

- name: Set BIND config options
  template:
    src: etc_sysconfig_named.j2
    dest: "/etc/sysconfig/named"
    owner: root
    group: root
    mode: '0644'
  notify: restart bind
  tags: bind

- name: Open Firewall
  firewalld:
    service: dns
    permanent: true
    state: enabled
  tags: bind
  notify:
    - restart firewalld

- name: Create serial
  command: date +%y%m%d%H%M
  register: timestamp
  changed_when: false
  tags: bind
- include: master.yml
  when: bind_zone_master_server_ip in ansible_all_ipv4_addresses

- include: slave.yml
  when: bind_zone_master_server_ip not in ansible_all_ipv4_addresses

- name: Start BIND service
  service:
    name: named
    state: started
    enabled: yes
  tags: bind
